name = "Parameters"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
author = ["Mauro Werder <mauro3@runbox.com>"]
version = "0.12.3"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
OrderedCollections = "1"
UnPack = "0.1, 1.0"
julia = "1"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["REPL", "Test", "Markdown"]
